name: Github repository information
description: Update Github repository information by JSON.

inputs:
  json-path:
    description: JSON path
    required: True

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
