name: Update Github repository information

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update Github repo info
        uses: Darkborderman/github-actions/github-repo-info@master
        with:
          json_path: metadata.json
